# This config contains the essential (previously) hard-coded values, that can be changed
# in train.py
train:
    # fix is GCNConv with radius_graph, dyn is EdgeConv, simple is only self-connected
    mode: fix     # fix, dyn or simple

    batch_size: 120
    validation_split: 0.2
        
    # optimizer: AdamW
    learning_rate: 0.001

    # scheduler: ReduceLROnPlateau
    factor: 0.5
    patience: 500
    threshold: 0.05
    
    max_epoch: 30
    
    # edge_index: radius_graph
    deltaR: 0.4
    max_num_neighbors: 500
    loop: True
    
    dataset: /local/scratch/ssd/nshadskiy/DeepMET_data/znunu_60k_fix_dxyz/

    ckpt: final/num_layers_1
    
    
# net.py
net:
    continuous_dim: 7
    categorical_dim: 3
    output_dim: 1
    hidden_dim: 32
    conv_depth: 1
    

# graph_met_network.py
graph_met_network:
    # for knn_graph
    k: 10

# variables and functions that are not changed often -> therefore you have to change them manually both: Here and in the python file
# in train.py

type_of_net: 
    update: GCNConv
    edge_index: radius_graph
    Embedding: True
    inputs: ["pX", "pY", "pT", "eta", "d0", "dz", "mass", "puppiWeight", "pdgId", "charge", "fromPV"]

# training
loss: MSE
